### ISSUE TITLE
Using yaml2solana 2 in CLI and deprecate the old yaml2solana

### ISSUE THREAD

**Issue by ghabxph** [ghabxph/yaml2solana#14]
# Tasks:

- [x] **Task 1:** Use yaml2solana in CLI
- [x] **Task 2:** Refactor the code base to not to use the old yaml2solana and migrate everything to yaml2solana 2 class
- [x] **Task 3:** Rename yaml2solana2 into yaml2solana, and remove old codes (old yaml2solana)
