### ISSUE TITLE
Extend CLI from SDK for customizability

### ISSUE THREAD

**Issue by ghabxph** [ghabxph/yaml2solana#39]
## TODO (Any order)

- [x] Instruction Bundles
  - [x] SDK
  - [x] CLI
- [x] Account Decoder
  - [x] SDK
  - [x] CLI (Utils)
- [x] Account overrider
  - [x] Override lamport amount in testWallet
  - [x] Account data override (now that we have account decoder, this is now possible)
- [x] Extend CLI from SDK for customizability
  - [x] Dynamic instruction
  - [x] Be able to start CLI via SDK / Importing its entrypoint
- [x] Make sure things are working.
